
appointmentType = {
    "4036" : "POLICIA - RECOGIDA DE TARJETA DE IDENTIDAD DE EXTRANJERO (TIE)",
    "4092" : "POLICIA - TÍTULOS DE VIAJE",
    "4067" : "POLICIA- EXPEDICIÓN/RENOVACIÓN DE DOCUMENTOS DE SOLICITANTES DE ASILO",
    "4078" : "POLICIA- SOLICITUD ASILO",
    "20": "POLICIA-AUTORIZACIÓN DE REGRESO",
    "4037" : "POLICIA-CARTA DE INVITACIÓN",
    "4038" : "POLICIA-CERTIFICADO DE REGISTRO DE CIUDADANO DE LA U.E.",
    "4049" : "POLICIA-CERTIFICADOS (DE RESIDENCIA, DE NO RESIDENCIA Y DE CONCORDANCIA)",
    "4096" : "POLICIA-CERTIFICADOS Y ASIGNACION NIE",
    "4079" : "POLICIA-CERTIFICADOS Y ASIGNACION NIE (NO COMUNITARIOS)",
    "4094" : "POLICÍA-EXP.TARJETA ASOCIADA AL ACUERDO DE RETIRADA CIUDADANOS BRITÁNICOS Y SUS FAMILIARES (BREXIT)",
    "4010" : "POLICIA-TOMA DE HUELLAS (EXPEDICIÓN DE TARJETA) Y RENOVACIÓN DE TARJETA DE LARGA DURACIÓN",
}